### ISSUE TITLE
No effects with Hue

### ISSUE THREAD

**Issue by vingerha** [fairecasoimeme/ZigWS2812_controller#8]
Hi, I do understand that you discontinued this product but I acquired this just now and would like to understand if I can improve it with firmware. It connects with Hue but I can only change color, no effects whatsoever and that is not why I want WS2812 of course.
The device states v1.1 but how would I know which firmware is on it and how would I update it?

Thanks for any response

EDIT, I connected it to Z2M and this works a bit better, it states firmware 0001-0004 ... so I guess it is the latest you have?
In that case, any clue why Hue only allows colors and no effects? Z2M does allow it but I need it for my kid who only has HUE

**Comment by fairecasoimeme** [comment]
the problem is due to zigbee. You can't drive each LED to do effect or color with cluster/attribute/endpoint even if you use WS2812

**Comment by vingerha** [comment]
Much appreciated your response....I did a lot of research but never found this dwonside before buying a zigbee controller. I guess I only have a wifi (or prprietary) solution then, will check ESP instead....again: THANKS!
